// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson87300af1DecodeBirdwatchModel(in *jlexer.Lexer, out *SignalSummary) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "y":
			out.CenterLatitude = float32(in.Float32())
		case "x":
			out.CenterLongitude = float32(in.Float32())
		case "r":
			out.MaxRadius = float32(in.Float32())
		case "d":
			out.Distance = float32(in.Float32())
		case "t":
			out.Timespan = uint32(in.Uint32())
		case "a":
			out.Account = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson87300af1EncodeBirdwatchModel(out *jwriter.Writer, in SignalSummary) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"y\":"
		out.RawString(prefix[1:])
		out.Float32(float32(in.CenterLatitude))
	}
	{
		const prefix string = ",\"x\":"
		out.RawString(prefix)
		out.Float32(float32(in.CenterLongitude))
	}
	{
		const prefix string = ",\"r\":"
		out.RawString(prefix)
		out.Float32(float32(in.MaxRadius))
	}
	{
		const prefix string = ",\"d\":"
		out.RawString(prefix)
		out.Float32(float32(in.Distance))
	}
	{
		const prefix string = ",\"t\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.Timespan))
	}
	{
		const prefix string = ",\"a\":"
		out.RawString(prefix)
		out.String(string(in.Account))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SignalSummary) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson87300af1EncodeBirdwatchModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SignalSummary) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson87300af1EncodeBirdwatchModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SignalSummary) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson87300af1DecodeBirdwatchModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SignalSummary) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson87300af1DecodeBirdwatchModel(l, v)
}
