// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson33df6060DecodeBirdwatchModel(in *jlexer.Lexer, out *Signal) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "i":
			out.DeviceId = string(in.String())
		case "y":
			out.Latitude = float32(in.Float32())
		case "x":
			out.Longitude = float32(in.Float32())
		case "t":
			out.Timestamp = uint32(in.Uint32())
		case "s":
			out.Signature = string(in.String())
		case "a":
			out.Account = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson33df6060EncodeBirdwatchModel(out *jwriter.Writer, in Signal) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"i\":"
		out.RawString(prefix[1:])
		out.String(string(in.DeviceId))
	}
	{
		const prefix string = ",\"y\":"
		out.RawString(prefix)
		out.Float32(float32(in.Latitude))
	}
	{
		const prefix string = ",\"x\":"
		out.RawString(prefix)
		out.Float32(float32(in.Longitude))
	}
	{
		const prefix string = ",\"t\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.Timestamp))
	}
	{
		const prefix string = ",\"s\":"
		out.RawString(prefix)
		out.String(string(in.Signature))
	}
	{
		const prefix string = ",\"a\":"
		out.RawString(prefix)
		out.String(string(in.Account))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Signal) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson33df6060EncodeBirdwatchModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Signal) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson33df6060EncodeBirdwatchModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Signal) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson33df6060DecodeBirdwatchModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Signal) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson33df6060DecodeBirdwatchModel(l, v)
}
